[package]
name = "eke"
version = "0.1.0"
edition = "2021"

[dependencies]
aes = "0.8.4"
anyhow = "1.0.86"
bincode = "1.3.3"
clap = { version = "4.5.7", features = ["derive"] }
ctr = "0.9.2"
hkdf = "0.12.4"
rand = "0.8.5"
rsa = { version = "0.9.6", features = ["serde"] }
sha2 = "0.10.8"
