test:
  image: jiegec/rust:1.63-bullseye-tuna
  script:
    - cargo build || cargo build || cargo build
    - cargo test -- --test-threads=1

fmt:
  image: cimg/rust:1.63
  script:
    - cargo fmt --check
