`timescale 1ns / 1ps
`include "frame_datapath.vh"
`include "cpu/rv32i_cpu.vh"

/* Tsinghua Advanced Networking Labs */

module tanlabs
#(
    parameter SIM = 0
)
(
    input wire RST,
    input wire BTN,

    input wire gtclk_125_p,
    input wire gtclk_125_n,

    input  wire [ 3:0] touch_btn,  // BTN1~BTN4，按钮开关，按下时为 1
    input  wire [15:0] dip_sw,     // 16 位拨码开关，拨到“ON”时为 1
    output wire [ 7:0] dpy0,       // 数码管低位信号，包括小数点，输出 1 点亮
    output wire [ 7:0] dpy1,       // 数码管高位信号，包括小数点，输出 1 点亮

    output wire [15:0] led,

    output wire uart_tx,
    input wire uart_rx,

    // SFP:
    // +-+-+
    // |0|2|
    // +-+-+
    // |1|3|
    // +-+-+
    input wire [3:0] sfp_rx_los,
    input wire [3:0] sfp_rx_p,
    input wire [3:0] sfp_rx_n,
    output wire [3:0] sfp_tx_dis,
    output wire [3:0] sfp_tx_p,
    output wire [3:0] sfp_tx_n,
    output wire [3:0] sfp_link,
    output wire [3:0] sfp_act,

    // I2C for SFP, unused.
    input wire sfp_sda,
    input wire sfp_scl,

    // BaseRAM
    output wire base_ram_ce_n,
    output wire base_ram_oe_n,
    output wire base_ram_we_n,
    output wire[3:0] base_ram_be_n,
    output wire [20:0] base_ram_addr,
    inout wire [31:0] base_ram_data
);

    localparam DATA_WIDTH = 64;
    localparam ID_WIDTH = 3;

    wire [4:0] debug_ingress_interconnect_ready;
    wire debug_datapath_fifo_ready;
    wire debug_egress_interconnect_ready;

    wire reset_in = RST;
    wire locked0;
    wire gtref_clk;  // 125MHz for the PHY/MAC IP core
    wire ref_clk;  // 200MHz for the PHY/MAC IP core

    clk_wiz_0 clk_wiz_0_i(
        .ref_clk_out(ref_clk),
        .reset(1'b0),
        .locked(locked0),
        .clk_in1(gtref_clk)
    );

    // clk_wiz_1 clk_wiz_1_i(
    //     .core_clk_out(core_clk),
    //     .reset(1'b0),
    //     .locked(locked1),
    //     .clk_in1(gtref_clk)
    // );

    wire reset_not_sync = reset_in || !locked0 /*|| !locked1*/;  // reset components

    wire mmcm_locked_out;
    wire rxuserclk_out;
    wire rxuserclk2_out;
    wire userclk_out;
    wire userclk2_out;
    wire pma_reset_out;
    wire gt0_qplloutclk_out;
    wire gt0_qplloutrefclk_out;
    wire gtref_clk_out;
    wire gtref_clk_buf_out;

    assign gtref_clk = gtref_clk_buf_out;
    wire eth_clk = userclk2_out;  // README: This is the main clock for frame processing logic,
    // 125MHz generated by the PHY/MAC IP core. 8 AXI-Streams are in this clock domain.

    wire reset_eth_not_sync = reset_in || !mmcm_locked_out;
    wire reset_eth_not_booted;
    wire reset_eth;
    wire bootloader_finished;
    reset_sync reset_sync_reset_eth(
        .clk(eth_clk),
        .i(reset_eth_not_sync),
        .o(reset_eth_not_booted)
    );
    assign reset_eth = reset_eth_not_booted || !bootloader_finished;

    wire [7:0] eth_tx8_data [0:4];
    wire eth_tx8_last [0:4];
    wire eth_tx8_ready [0:4];
    wire eth_tx8_user [0:4];
    wire eth_tx8_valid [0:4];

    wire [7:0] eth_rx8_data [0:4];
    wire eth_rx8_last [0:4];
    wire eth_rx8_user [0:4];
    wire eth_rx8_valid [0:4];

    genvar i;
    generate
        if (!SIM)
        begin : phy_mac_ip_cores
            // Instantiate 4 PHY/MAC IP cores.

            assign sfp_tx_dis[0] = 1'b0;
            axi_ethernet_0 axi_ethernet_0_i(
                .mac_irq(),
                .tx_mac_aclk(),
                .rx_mac_aclk(),
                .tx_reset(),
                .rx_reset(),

                .glbl_rst(reset_not_sync),

                .mmcm_locked_out(mmcm_locked_out),
                .rxuserclk_out(rxuserclk_out),
                .rxuserclk2_out(rxuserclk2_out),
                .userclk_out(userclk_out),
                .userclk2_out(userclk2_out),
                .pma_reset_out(pma_reset_out),
                .gt0_qplloutclk_out(gt0_qplloutclk_out),
                .gt0_qplloutrefclk_out(gt0_qplloutrefclk_out),
                .gtref_clk_out(gtref_clk_out),
                .gtref_clk_buf_out(gtref_clk_buf_out),

                .ref_clk(ref_clk),

                .s_axi_lite_resetn(~reset_eth),
                .s_axi_lite_clk(eth_clk),
                .s_axi_araddr(0),
                .s_axi_arready(),
                .s_axi_arvalid(0),
                .s_axi_awaddr(0),
                .s_axi_awready(),
                .s_axi_awvalid(0),
                .s_axi_bready(0),
                .s_axi_bresp(),
                .s_axi_bvalid(),
                .s_axi_rdata(),
                .s_axi_rready(0),
                .s_axi_rresp(),
                .s_axi_rvalid(),
                .s_axi_wdata(0),
                .s_axi_wready(),
                .s_axi_wvalid(0),

                .s_axis_tx_tdata(eth_tx8_data[0]),
                .s_axis_tx_tlast(eth_tx8_last[0]),
                .s_axis_tx_tready(eth_tx8_ready[0]),
                .s_axis_tx_tuser(eth_tx8_user[0]),
                .s_axis_tx_tvalid(eth_tx8_valid[0]),

                .m_axis_rx_tdata(eth_rx8_data[0]),
                .m_axis_rx_tlast(eth_rx8_last[0]),
                .m_axis_rx_tuser(eth_rx8_user[0]),
                .m_axis_rx_tvalid(eth_rx8_valid[0]),

                .s_axis_pause_tdata(0),
                .s_axis_pause_tvalid(0),

                .rx_statistics_statistics_data(),
                .rx_statistics_statistics_valid(),
                .tx_statistics_statistics_data(),
                .tx_statistics_statistics_valid(),

                .tx_ifg_delay(8'h00),
                .status_vector(),
                .signal_detect(~sfp_rx_los[0]),

                .sfp_rxn(sfp_rx_n[0]),
                .sfp_rxp(sfp_rx_p[0]),
                .sfp_txn(sfp_tx_n[0]),
                .sfp_txp(sfp_tx_p[0]),

                .mgt_clk_clk_n(gtclk_125_n),
                .mgt_clk_clk_p(gtclk_125_p)
            );

            for (i = 1; i < 4; i = i + 1)
            begin
                assign sfp_tx_dis[i] = 1'b0;
                axi_ethernet_noshared axi_ethernet_noshared_i(
                    .mac_irq(),
                    .tx_mac_aclk(),
                    .rx_mac_aclk(),
                    .tx_reset(),
                    .rx_reset(),

                    .glbl_rst(reset_not_sync),

                    .mmcm_locked(mmcm_locked_out),
                    .mmcm_reset_out(),
                    .rxuserclk(rxuserclk_out),
                    .rxuserclk2(rxuserclk2_out),
                    .userclk(userclk_out),
                    .userclk2(userclk2_out),
                    .pma_reset(pma_reset_out),
                    .rxoutclk(),
                    .txoutclk(),
                    .gt0_qplloutclk_in(gt0_qplloutclk_out),
                    .gt0_qplloutrefclk_in(gt0_qplloutrefclk_out),
                    .gtref_clk(gtref_clk_out),
                    .gtref_clk_buf(gtref_clk_buf_out),

                    .ref_clk(ref_clk),

                    .s_axi_lite_resetn(~reset_eth),
                    .s_axi_lite_clk(eth_clk),
                    .s_axi_araddr(0),
                    .s_axi_arready(),
                    .s_axi_arvalid(0),
                    .s_axi_awaddr(0),
                    .s_axi_awready(),
                    .s_axi_awvalid(0),
                    .s_axi_bready(0),
                    .s_axi_bresp(),
                    .s_axi_bvalid(),
                    .s_axi_rdata(),
                    .s_axi_rready(0),
                    .s_axi_rresp(),
                    .s_axi_rvalid(),
                    .s_axi_wdata(0),
                    .s_axi_wready(),
                    .s_axi_wvalid(0),

                    .s_axis_tx_tdata(eth_tx8_data[i]),
                    .s_axis_tx_tlast(eth_tx8_last[i]),
                    .s_axis_tx_tready(eth_tx8_ready[i]),
                    .s_axis_tx_tuser(eth_tx8_user[i]),
                    .s_axis_tx_tvalid(eth_tx8_valid[i]),

                    .m_axis_rx_tdata(eth_rx8_data[i]),
                    .m_axis_rx_tlast(eth_rx8_last[i]),
                    .m_axis_rx_tuser(eth_rx8_user[i]),
                    .m_axis_rx_tvalid(eth_rx8_valid[i]),

                    .s_axis_pause_tdata(0),
                    .s_axis_pause_tvalid(0),

                    .rx_statistics_statistics_data(),
                    .rx_statistics_statistics_valid(),
                    .tx_statistics_statistics_data(),
                    .tx_statistics_statistics_valid(),

                    .tx_ifg_delay(8'h00),
                    .status_vector(),
                    .signal_detect(~sfp_rx_los[i]),

                    .sfp_rxn(sfp_rx_n[i]),
                    .sfp_rxp(sfp_rx_p[i]),
                    .sfp_txn(sfp_tx_n[i]),
                    .sfp_txp(sfp_tx_p[i])
                );
            end
        end
        else
        begin : axis_models
            // For simulation.
            assign gtref_clk_buf_out = gtclk_125_p;
            assign userclk2_out = gtclk_125_p;
            assign mmcm_locked_out = 1'b1;

            assign sfp_tx_dis = 0;
            assign sfp_tx_p = 0;
            assign sfp_tx_n = 0;

            wire [DATA_WIDTH - 1:0] in_data;
            wire [DATA_WIDTH / 8 - 1:0] in_keep;
            wire in_last;
            wire [DATA_WIDTH / 8 - 1:0] in_user;
            wire [ID_WIDTH - 1:0] in_id;
            wire in_valid;
            wire in_ready;

            axis_model axis_model_i(
                .clk(eth_clk),
                .reset(reset_eth),

                .m_data(in_data),
                .m_keep(in_keep),
                .m_last(in_last),
                .m_user(in_user),
                .m_id(in_id),
                .m_valid(in_valid),
                .m_ready(in_ready)
            );

            wire [DATA_WIDTH - 1:0] sim_tx_data [0:3];
            wire [DATA_WIDTH / 8 - 1:0] sim_tx_keep [0:3];
            wire sim_tx_last [0:3];
            wire sim_tx_ready [0:3];
            wire [DATA_WIDTH / 8 - 1:0] sim_tx_user [0:3];
            wire sim_tx_valid [0:3];

            axis_interconnect_egress axis_interconnect_sim_in_i(
                .ACLK(eth_clk),
                .ARESETN(~reset_eth),

                .S00_AXIS_ACLK(eth_clk),
                .S00_AXIS_ARESETN(~reset_eth),
                .S00_AXIS_TVALID(in_valid),
                .S00_AXIS_TREADY(in_ready),
                .S00_AXIS_TDATA(in_data),
                .S00_AXIS_TKEEP(in_keep),
                .S00_AXIS_TLAST(in_last),
                .S00_AXIS_TDEST(in_id),
                .S00_AXIS_TUSER(in_user),

                .M00_AXIS_ACLK(eth_clk),
                .M00_AXIS_ARESETN(~reset_eth),
                .M00_AXIS_TVALID(sim_tx_valid[0]),
                .M00_AXIS_TREADY(sim_tx_ready[0]),
                .M00_AXIS_TDATA(sim_tx_data[0]),
                .M00_AXIS_TKEEP(sim_tx_keep[0]),
                .M00_AXIS_TLAST(sim_tx_last[0]),
                .M00_AXIS_TDEST(),
                .M00_AXIS_TUSER(sim_tx_user[0]),

                .M01_AXIS_ACLK(eth_clk),
                .M01_AXIS_ARESETN(~reset_eth),
                .M01_AXIS_TVALID(sim_tx_valid[1]),
                .M01_AXIS_TREADY(sim_tx_ready[1]),
                .M01_AXIS_TDATA(sim_tx_data[1]),
                .M01_AXIS_TKEEP(sim_tx_keep[1]),
                .M01_AXIS_TLAST(sim_tx_last[1]),
                .M01_AXIS_TDEST(),
                .M01_AXIS_TUSER(sim_tx_user[1]),

                .M02_AXIS_ACLK(eth_clk),
                .M02_AXIS_ARESETN(~reset_eth),
                .M02_AXIS_TVALID(sim_tx_valid[2]),
                .M02_AXIS_TREADY(sim_tx_ready[2]),
                .M02_AXIS_TDATA(sim_tx_data[2]),
                .M02_AXIS_TKEEP(sim_tx_keep[2]),
                .M02_AXIS_TLAST(sim_tx_last[2]),
                .M02_AXIS_TDEST(),
                .M02_AXIS_TUSER(sim_tx_user[2]),

                .M03_AXIS_ACLK(eth_clk),
                .M03_AXIS_ARESETN(~reset_eth),
                .M03_AXIS_TVALID(sim_tx_valid[3]),
                .M03_AXIS_TREADY(sim_tx_ready[3]),
                .M03_AXIS_TDATA(sim_tx_data[3]),
                .M03_AXIS_TKEEP(sim_tx_keep[3]),
                .M03_AXIS_TLAST(sim_tx_last[3]),
                .M03_AXIS_TDEST(),
                .M03_AXIS_TUSER(sim_tx_user[3]),

                .M04_AXIS_ACLK(eth_clk),
                .M04_AXIS_ARESETN(~reset_eth),
                .M04_AXIS_TVALID(),
                .M04_AXIS_TREADY(1'b1),
                .M04_AXIS_TDATA(),
                .M04_AXIS_TKEEP(),
                .M04_AXIS_TLAST(),
                .M04_AXIS_TDEST(),
                .M04_AXIS_TUSER(),

                .S00_DECODE_ERR()
            );

            for (i = 0; i < 4; i = i + 1)
            begin
                axis_dwidth_converter_64_8 axis_dwidth_converter_64_8_i(
                    .aclk(eth_clk),
                    .aresetn(~reset_eth),

                    .s_axis_tvalid(sim_tx_valid[i]),
                    .s_axis_tready(sim_tx_ready[i]),
                    .s_axis_tdata(sim_tx_data[i]),
                    .s_axis_tkeep(sim_tx_keep[i]),
                    .s_axis_tlast(sim_tx_last[i]),
                    .s_axis_tuser(sim_tx_user[i]),

                    .m_axis_tvalid(eth_rx8_valid[i]),
                    .m_axis_tready(debug_ingress_interconnect_ready[i]),  // FIXME
                    .m_axis_tdata(eth_rx8_data[i]),
                    .m_axis_tkeep(),
                    .m_axis_tlast(eth_rx8_last[i]),
                    .m_axis_tuser(eth_rx8_user[i])
                );
            end

            wire [DATA_WIDTH - 1:0] out_data;
            wire [DATA_WIDTH / 8 - 1:0] out_keep;
            wire out_last;
            wire [DATA_WIDTH / 8 - 1:0] out_user;
            wire [ID_WIDTH - 1:0] out_dest;
            wire out_valid;
            wire out_ready;

            axis_interconnect_ingress axis_interconnect_sim_out_i(
                .ACLK(eth_clk),
                .ARESETN(~reset_eth),

                .S00_AXIS_ACLK(eth_clk),
                .S00_AXIS_ARESETN(~reset_eth),
                .S00_AXIS_TVALID(eth_tx8_valid[0]),
                .S00_AXIS_TREADY(eth_tx8_ready[0]),
                .S00_AXIS_TDATA(eth_tx8_data[0]),
                .S00_AXIS_TKEEP(1'b1),
                .S00_AXIS_TLAST(eth_tx8_last[0]),
                .S00_AXIS_TID(3'd0),
                .S00_AXIS_TUSER(eth_tx8_user[0]),

                .S01_AXIS_ACLK(eth_clk),
                .S01_AXIS_ARESETN(~reset_eth),
                .S01_AXIS_TVALID(eth_tx8_valid[1]),
                .S01_AXIS_TREADY(eth_tx8_ready[1]),
                .S01_AXIS_TDATA(eth_tx8_data[1]),
                .S01_AXIS_TKEEP(1'b1),
                .S01_AXIS_TLAST(eth_tx8_last[1]),
                .S01_AXIS_TID(3'd1),
                .S01_AXIS_TUSER(eth_tx8_user[1]),

                .S02_AXIS_ACLK(eth_clk),
                .S02_AXIS_ARESETN(~reset_eth),
                .S02_AXIS_TVALID(eth_tx8_valid[2]),
                .S02_AXIS_TREADY(eth_tx8_ready[2]),
                .S02_AXIS_TDATA(eth_tx8_data[2]),
                .S02_AXIS_TKEEP(1'b1),
                .S02_AXIS_TLAST(eth_tx8_last[2]),
                .S02_AXIS_TID(3'd2),
                .S02_AXIS_TUSER(eth_tx8_user[2]),

                .S03_AXIS_ACLK(eth_clk),
                .S03_AXIS_ARESETN(~reset_eth),
                .S03_AXIS_TVALID(eth_tx8_valid[3]),
                .S03_AXIS_TREADY(eth_tx8_ready[3]),
                .S03_AXIS_TDATA(eth_tx8_data[3]),
                .S03_AXIS_TKEEP(1'b1),
                .S03_AXIS_TLAST(eth_tx8_last[3]),
                .S03_AXIS_TID(3'd3),
                .S03_AXIS_TUSER(eth_tx8_user[3]),

                .S04_AXIS_ACLK(eth_clk),
                .S04_AXIS_ARESETN(~reset_eth),
                .S04_AXIS_TVALID(1'b0),
                .S04_AXIS_TREADY(),
                .S04_AXIS_TDATA(0),
                .S04_AXIS_TKEEP(1'b1),
                .S04_AXIS_TLAST(1'b0),
                .S04_AXIS_TID(3'd4),
                .S04_AXIS_TUSER(1'b0),

                .M00_AXIS_ACLK(eth_clk),
                .M00_AXIS_ARESETN(~reset_eth),
                .M00_AXIS_TVALID(out_valid),
                .M00_AXIS_TREADY(out_ready),
                .M00_AXIS_TDATA(out_data),
                .M00_AXIS_TKEEP(out_keep),
                .M00_AXIS_TLAST(out_last),
                .M00_AXIS_TID(out_dest),
                .M00_AXIS_TUSER(out_user),

                .S00_ARB_REQ_SUPPRESS(0),
                .S01_ARB_REQ_SUPPRESS(0),
                .S02_ARB_REQ_SUPPRESS(0),
                .S03_ARB_REQ_SUPPRESS(0),
                .S04_ARB_REQ_SUPPRESS(0),

                .S00_FIFO_DATA_COUNT(),
                .S01_FIFO_DATA_COUNT(),
                .S02_FIFO_DATA_COUNT(),
                .S03_FIFO_DATA_COUNT(),
                .S04_FIFO_DATA_COUNT()
            );

            axis_receiver axis_receiver_i(
                .clk(eth_clk),
                .reset(reset_eth),

                .s_data(out_data),
                .s_keep(out_keep),
                .s_last(out_last),
                .s_user(out_user),
                .s_dest(out_dest),
                .s_valid(out_valid),
                .s_ready(out_ready)
            );
        end
    endgenerate

    wire [7:0] internal_tx_data;
    wire internal_tx_last;
    wire internal_tx_user;
    wire internal_tx_valid;
    assign eth_rx8_data[4] = internal_tx_data;
    assign eth_rx8_last[4] = internal_tx_last;
    assign eth_rx8_user[4] = internal_tx_user;
    assign eth_rx8_valid[4] = internal_tx_valid;

    wire [7:0] internal_rx_data = eth_tx8_data[4];
    wire internal_rx_last = eth_tx8_last[4];
    wire internal_rx_user = eth_tx8_user[4];
    wire internal_rx_valid = eth_tx8_valid[4];
    wire internal_rx_ready;
    assign eth_tx8_ready[4] = internal_rx_ready;

    // README: internal_tx_* and internal_rx_* are left for internal use.
    // You can connect them with your CPU to transfer frames between the router part and the CPU part,
    // and you may need to write some logic to receive from internal_rx_*, store data to some memory,
    // read data from some memory, and send to internal_tx_*.
    // You can also transfer frames in other ways.

    wire [7:0] sfp_led;
    led_delayer led_delayer_i(
        .clk(eth_clk),
        .reset(reset_eth),
        .in_led({~sfp_rx_los[3],
                 ~sfp_rx_los[2],
                 ~sfp_rx_los[1],
                 ~sfp_rx_los[0],
                 (eth_tx8_valid[3] & eth_tx8_ready[3]) | eth_rx8_valid[3],
                 (eth_tx8_valid[2] & eth_tx8_ready[2]) | eth_rx8_valid[2],
                 (eth_tx8_valid[1] & eth_tx8_ready[1]) | eth_rx8_valid[1],
                 (eth_tx8_valid[0] & eth_tx8_ready[0]) | eth_rx8_valid[0]}),
        .out_led(sfp_led)
    );
    assign {sfp_link, sfp_act} = sfp_led;

    wire [DATA_WIDTH - 1:0] eth_rx_data;
    wire [DATA_WIDTH / 8 - 1:0] eth_rx_keep;
    wire eth_rx_last;
    wire [DATA_WIDTH / 8 - 1:0] eth_rx_user;
    wire [ID_WIDTH - 1:0] eth_rx_id;
    wire eth_rx_valid;

    axis_interconnect_ingress axis_interconnect_ingress_i(
        .ACLK(eth_clk),
        .ARESETN(~reset_eth),

        .S00_AXIS_ACLK(eth_clk),
        .S00_AXIS_ARESETN(~reset_eth),
        .S00_AXIS_TVALID(eth_rx8_valid[0]),
        .S00_AXIS_TREADY(debug_ingress_interconnect_ready[0]),
        .S00_AXIS_TDATA(eth_rx8_data[0]),
        .S00_AXIS_TKEEP(1'b1),
        .S00_AXIS_TLAST(eth_rx8_last[0]),
        .S00_AXIS_TID(3'd0),
        .S00_AXIS_TUSER(eth_rx8_user[0]),

        .S01_AXIS_ACLK(eth_clk),
        .S01_AXIS_ARESETN(~reset_eth),
        .S01_AXIS_TVALID(eth_rx8_valid[1]),
        .S01_AXIS_TREADY(debug_ingress_interconnect_ready[1]),
        .S01_AXIS_TDATA(eth_rx8_data[1]),
        .S01_AXIS_TKEEP(1'b1),
        .S01_AXIS_TLAST(eth_rx8_last[1]),
        .S01_AXIS_TID(3'd1),
        .S01_AXIS_TUSER(eth_rx8_user[1]),

        .S02_AXIS_ACLK(eth_clk),
        .S02_AXIS_ARESETN(~reset_eth),
        .S02_AXIS_TVALID(eth_rx8_valid[2]),
        .S02_AXIS_TREADY(debug_ingress_interconnect_ready[2]),
        .S02_AXIS_TDATA(eth_rx8_data[2]),
        .S02_AXIS_TKEEP(1'b1),
        .S02_AXIS_TLAST(eth_rx8_last[2]),
        .S02_AXIS_TID(3'd2),
        .S02_AXIS_TUSER(eth_rx8_user[2]),

        .S03_AXIS_ACLK(eth_clk),
        .S03_AXIS_ARESETN(~reset_eth),
        .S03_AXIS_TVALID(eth_rx8_valid[3]),
        .S03_AXIS_TREADY(debug_ingress_interconnect_ready[3]),
        .S03_AXIS_TDATA(eth_rx8_data[3]),
        .S03_AXIS_TKEEP(1'b1),
        .S03_AXIS_TLAST(eth_rx8_last[3]),
        .S03_AXIS_TID(3'd3),
        .S03_AXIS_TUSER(eth_rx8_user[3]),

        .S04_AXIS_ACLK(eth_clk),
        .S04_AXIS_ARESETN(~reset_eth),
        .S04_AXIS_TVALID(eth_rx8_valid[4]),
        .S04_AXIS_TREADY(debug_ingress_interconnect_ready[4]),
        .S04_AXIS_TDATA(eth_rx8_data[4]),
        .S04_AXIS_TKEEP(1'b1),
        .S04_AXIS_TLAST(eth_rx8_last[4]),
        .S04_AXIS_TID(3'd4),
        .S04_AXIS_TUSER(eth_rx8_user[4]),

        .M00_AXIS_ACLK(eth_clk),
        .M00_AXIS_ARESETN(~reset_eth),
        .M00_AXIS_TVALID(eth_rx_valid),
        .M00_AXIS_TREADY(1'b1),
        .M00_AXIS_TDATA(eth_rx_data),
        .M00_AXIS_TKEEP(eth_rx_keep),
        .M00_AXIS_TLAST(eth_rx_last),
        .M00_AXIS_TID(eth_rx_id),
        .M00_AXIS_TUSER(eth_rx_user),

        .S00_ARB_REQ_SUPPRESS(0),
        .S01_ARB_REQ_SUPPRESS(0),
        .S02_ARB_REQ_SUPPRESS(0),
        .S03_ARB_REQ_SUPPRESS(0),
        .S04_ARB_REQ_SUPPRESS(0),

        .S00_FIFO_DATA_COUNT(),
        .S01_FIFO_DATA_COUNT(),
        .S02_FIFO_DATA_COUNT(),
        .S03_FIFO_DATA_COUNT(),
        .S04_FIFO_DATA_COUNT()
    );

    wire [DATA_WIDTH - 1:0] dp_rx_data;
    wire [DATA_WIDTH / 8 - 1:0] dp_rx_keep;
    wire dp_rx_last;
    wire [DATA_WIDTH / 8 - 1:0] dp_rx_user;
    wire [ID_WIDTH - 1:0] dp_rx_id;
    wire dp_rx_valid;
    wire dp_rx_ready;

    frame_datapath_fifo
    #(
        .ENABLE(1),  // README: enable this if your datapath may block.
        .DATA_WIDTH(DATA_WIDTH),
        .ID_WIDTH(ID_WIDTH)
    )
    frame_datapath_fifo_i(
        .eth_clk(eth_clk),
        .reset(reset_eth),

        .s_data(eth_rx_data),
        .s_keep(eth_rx_keep),
        .s_last(eth_rx_last),
        .s_user(eth_rx_user),
        .s_id(eth_rx_id),
        .s_valid(eth_rx_valid),
        .s_ready(debug_datapath_fifo_ready),

        .m_data(dp_rx_data),
        .m_keep(dp_rx_keep),
        .m_last(dp_rx_last),
        .m_user(dp_rx_user),
        .m_id(dp_rx_id),
        .m_valid(dp_rx_valid),
        .m_ready(dp_rx_ready)
    );

    wire [DATA_WIDTH - 1:0] dp_tx_data;
    wire [DATA_WIDTH / 8 - 1:0] dp_tx_keep;
    wire dp_tx_last;
    wire [DATA_WIDTH / 8 - 1:0] dp_tx_user;
    wire [ID_WIDTH - 1:0] dp_tx_dest;
    wire dp_tx_valid;

    // Tree Bitmap memory

    wire [NODE_ADDR_WIDTH-1:0] bram_node_addr_ft[STAGE_NUM:1];
    bitmap_node bram_node_data_ft[STAGE_NUM:1];

    wire [NODE_ADDR_WIDTH-1:0] bram_node_addr_cpu[STAGE_NUM:1];
    bitmap_node bram_node_rdata_cpu[STAGE_NUM:1];
    bitmap_node bram_node_wdata_cpu[STAGE_NUM:1];
    wire bram_node_we_cpu[STAGE_NUM:1];

    wire [NODE_ADDR_WIDTH-1:0] bram_entry_addr_ft;
    wire [ENTRY_WIDTH-1:0] bram_entry_data_ft;

    wire [ENTRY_WIDTH-1:0] next_hop_addr_ft;
    next_hop_t next_hop_data_ft;

    wire [NODE_ADDR_WIDTH-1:0] bram_entry_addr_cpu;
    wire [ENTRY_WIDTH-1:0] bram_entry_rdata_cpu;
    wire [ENTRY_WIDTH-1:0] bram_entry_wdata_cpu;
    wire bram_entry_we_cpu;

    wire [ENTRY_WIDTH-1:0] next_hop_addr_cpu;
    next_hop_t next_hop_rdata_cpu;
    next_hop_t next_hop_wdata_cpu;
    wire next_hop_we_cpu;

    bram_node_pool_1 bram_node_pool_1_i (
        .clka(eth_clk),
        .addra(bram_node_addr_ft[2]),
        .douta(bram_node_data_ft[2]),
        .dina(0),
        .wea(0),

        .clkb(eth_clk),
        .addrb(bram_node_addr_cpu[2]),
        .doutb(bram_node_rdata_cpu[2]),
        .dinb(bram_node_wdata_cpu[2]),
        .web(bram_node_we_cpu[2])
    );

    bram_node_pool_2 bram_node_pool_2_i (
        .clka(eth_clk),
        .addra(bram_node_addr_ft[3]),
        .douta(bram_node_data_ft[3]),
        .dina(0),
        .wea(0),

        .clkb(eth_clk),
        .addrb(bram_node_addr_cpu[3]),
        .doutb(bram_node_rdata_cpu[3]),
        .dinb(bram_node_wdata_cpu[3]),
        .web(bram_node_we_cpu[3])
    );

    generate
        for (i = 1; i <= STAGE_NUM; i = i + 1) begin
          if (i == 1 || i >= 4) begin
            bram_node_pool_empty bram_node_pool_empty_i (
                .clka(eth_clk),
                .addra(bram_node_addr_ft[i]),
                .douta(bram_node_data_ft[i]),
                .dina(0),
                .wea(0),

                .clkb(eth_clk),
                .addrb(bram_node_addr_cpu[i]),
                .doutb(bram_node_rdata_cpu[i]),
                .dinb(bram_node_wdata_cpu[i]),
                .web(bram_node_we_cpu[i])
            );
          end
        end
    endgenerate

    bram_entry_pool bram_entry_pool_i (
        .clka(eth_clk),
        .addra(bram_entry_addr_ft),
        .douta(bram_entry_data_ft),
        .dina(0),
        .wea(0),

        .clkb(eth_clk),
        .addrb(bram_entry_addr_cpu),
        .doutb(bram_entry_rdata_cpu),
        .dinb(bram_entry_wdata_cpu),
        .web(bram_entry_we_cpu)
    );

    lutram_nexthop_list nexthop_list (
        .clk(eth_clk),
        .we(next_hop_we_cpu),
        .a(next_hop_addr_cpu),
        .d(next_hop_wdata_cpu),
        .spo(next_hop_rdata_cpu),
        .dpra(next_hop_addr_ft),
        .dpo(next_hop_data_ft)
    );

    wire inst_we;
    wire [12:0] inst_addr;
    wire [31:0] inst_wdata;

    wire [47:0] mac_address [IF_NUM-1:0];
    wire [127:0] ip_address [IF_NUM-1:0];
    wire [127:0] solicited_ip_address [IF_NUM-1:0];
    wire [47:0] solicited_mac_address [IF_NUM-1:0];

    wbm_signal_i wbm_i;
    wbm_signal_o wbm_o;

    rv32i_cpu rv32i_cpu_i (
        .clk(eth_clk),
        .rst(reset_eth),

        .inst_we,
        .inst_addr,
        .inst_wdata,

        .m_wb_i(wbm_i),
        .m_wb_o(wbm_o)
    );

    logic        wbm_cyc_o;
    logic        wbm_stb_o;
    logic        wbm_ack_i;
    logic [31:0] wbm_adr_o;
    logic [31:0] wbm_dat_o;
    logic [31:0] wbm_dat_i;
    logic [ 3:0] wbm_sel_o;
    logic        wbm_we_o;

    always_comb begin
        wbm_i.ack = wbm_ack_i;
        wbm_i.dat = wbm_dat_i;

        wbm_cyc_o = wbm_o.cyc;
        wbm_stb_o = wbm_o.stb;
        wbm_we_o  = wbm_o.we;
        wbm_sel_o = wbm_o.sel;
        wbm_adr_o = wbm_o.adr;
        wbm_dat_o = wbm_o.dat;
    end

    // Wishbone MUX (Masters) => bus slaves
    wire wbs0_cyc_o;
    wire wbs0_stb_o;
    wire wbs0_ack_i;
    wire [31:0] wbs0_adr_o;
    wire [31:0] wbs0_dat_o;
    wire [31:0] wbs0_dat_i;
    wire [3:0] wbs0_sel_o;
    wire wbs0_we_o;

    wire wbs1_cyc_o;
    wire wbs1_stb_o;
    wire wbs1_ack_i;
    wire [31:0] wbs1_adr_o;
    wire [31:0] wbs1_dat_o;
    wire [31:0] wbs1_dat_i;
    wire [3:0] wbs1_sel_o;
    wire wbs1_we_o;

    wire wbs2_cyc_o;
    wire wbs2_stb_o;
    wire wbs2_ack_i;
    wire [31:0] wbs2_adr_o;
    wire [31:0] wbs2_dat_o;
    wire [31:0] wbs2_dat_i;
    wire [3:0] wbs2_sel_o;
    wire wbs2_we_o;

    wire wbs3_cyc_o;
    wire wbs3_stb_o;
    wire wbs3_ack_i;
    wire [31:0] wbs3_adr_o;
    wire [31:0] wbs3_dat_o;
    wire [31:0] wbs3_dat_i;
    wire [3:0] wbs3_sel_o;
    wire wbs3_we_o;

    wire wbs4_cyc_o;
    wire wbs4_stb_o;
    wire wbs4_ack_i;
    wire [31:0] wbs4_adr_o;
    wire [31:0] wbs4_dat_o;
    wire [31:0] wbs4_dat_i;
    wire [3:0] wbs4_sel_o;
    wire wbs4_we_o;

    wire wbs5_cyc_o;
    wire wbs5_stb_o;
    wire wbs5_ack_i;
    wire [31:0] wbs5_adr_o;
    wire [31:0] wbs5_dat_o;
    wire [31:0] wbs5_dat_i;
    wire [3:0] wbs5_sel_o;
    wire wbs5_we_o;

    wire wbs6_cyc_o;
    wire wbs6_stb_o;
    wire wbs6_ack_i;
    wire [31:0] wbs6_adr_o;
    wire [31:0] wbs6_dat_o;
    wire [31:0] wbs6_dat_i;
    wire [3:0] wbs6_sel_o;
    wire wbs6_we_o;

    wire wbs7_cyc_o;
    wire wbs7_stb_o;
    wire wbs7_ack_i;
    wire [31:0] wbs7_adr_o;
    wire [31:0] wbs7_dat_o;
    wire [31:0] wbs7_dat_i;
    wire [3:0] wbs7_sel_o;
    wire wbs7_we_o;

    wbm_signal_i wbam_i[2:0];
    wbm_signal_o wbam_o[2:0];
    wbm_signal_i wbas_o;
    wbm_signal_o wbas_i;

    wb_mux wb_mux_i (
        .clk(eth_clk),
        .rst(reset_eth),

        // Master interface (to CPU master)
        .wbm_adr_i(wbm_adr_o),
        .wbm_dat_i(wbm_dat_o),
        .wbm_dat_o(wbm_dat_i),
        .wbm_we_i (wbm_we_o),
        .wbm_sel_i(wbm_sel_o),
        .wbm_stb_i(wbm_stb_o),
        .wbm_ack_o(wbm_ack_i),
        .wbm_err_o(),
        .wbm_rty_o(),
        .wbm_cyc_i(wbm_cyc_o),

        // Slave interface 0 (to BaseRAM controller)
        // Address range: 0x8000_0000 ~ 0x807F_FFFF
        .wbs0_addr    (32'h8000_0000),
        .wbs0_addr_msk(32'hFF80_0000),

        .wbs0_adr_o(wbam_o[2].adr),
        .wbs0_dat_i(wbam_i[2].dat),
        .wbs0_dat_o(wbam_o[2].dat),
        .wbs0_we_o (wbam_o[2].we),
        .wbs0_sel_o(wbam_o[2].sel),
        .wbs0_stb_o(wbam_o[2].stb),
        .wbs0_ack_i(wbam_i[2].ack),
        .wbs0_err_i('0),
        .wbs0_rty_i('0),
        .wbs0_cyc_o(wbam_o[2].cyc),

        // Slave interface 1 (to entryPool controller)
        // Address range: 0x8080_0000 ~ 0x808F_FFFF
        .wbs1_addr    (32'h8080_0000),
        .wbs1_addr_msk(32'hFFF0_0000),

        .wbs1_adr_o(wbs1_adr_o),
        .wbs1_dat_i(wbs1_dat_i),
        .wbs1_dat_o(wbs1_dat_o),
        .wbs1_we_o (wbs1_we_o),
        .wbs1_sel_o(wbs1_sel_o),
        .wbs1_stb_o(wbs1_stb_o),
        .wbs1_ack_i(wbs1_ack_i),
        .wbs1_err_i('0),
        .wbs1_rty_i('0),
        .wbs1_cyc_o(wbs1_cyc_o),

        // Slave interface 2 (to nextHopList controller)
        // Address range: 0x8090_0000 ~ 0x809F_FFFF
        .wbs2_addr    (32'h8090_0000),
        .wbs2_addr_msk(32'hFFF0_0000),

        .wbs2_adr_o(wbs2_adr_o),
        .wbs2_dat_i(wbs2_dat_i),
        .wbs2_dat_o(wbs2_dat_o),
        .wbs2_we_o (wbs2_we_o),
        .wbs2_sel_o(wbs2_sel_o),
        .wbs2_stb_o(wbs2_stb_o),
        .wbs2_ack_i(wbs2_ack_i),
        .wbs2_err_i('0),
        .wbs2_rty_i('0),
        .wbs2_cyc_o(wbs2_cyc_o),

        // Slave interface 3 (to nodePool controller)
        // Address range: 0x8100_0000 ~ 0x81FF_FFFF
        .wbs3_addr    (32'h8100_0000),
        .wbs3_addr_msk(32'hFF00_0000),

        .wbs3_adr_o(wbs3_adr_o),
        .wbs3_dat_i(wbs3_dat_i),
        .wbs3_dat_o(wbs3_dat_o),
        .wbs3_we_o (wbs3_we_o),
        .wbs3_sel_o(wbs3_sel_o),
        .wbs3_stb_o(wbs3_stb_o),
        .wbs3_ack_i(wbs3_ack_i),
        .wbs3_err_i('0),
        .wbs3_rty_i('0),
        .wbs3_cyc_o(wbs3_cyc_o),

        // Slave interface 4 (to DMA controller)
        // Address range: 0x80a0_0000 ~ 0x80aF_FFFF
        .wbs4_addr    (32'h80a0_0000),
        .wbs4_addr_msk(32'hFFF0_0000),

        .wbs4_adr_o(wbs4_adr_o),
        .wbs4_dat_i(wbs4_dat_i),
        .wbs4_dat_o(wbs4_dat_o),
        .wbs4_we_o (wbs4_we_o),
        .wbs4_sel_o(wbs4_sel_o),
        .wbs4_stb_o(wbs4_stb_o),
        .wbs4_ack_i(wbs4_ack_i),
        .wbs4_err_i('0),
        .wbs4_rty_i('0),
        .wbs4_cyc_o(wbs4_cyc_o),

        // Slave interface 5 (to DPY controller)
        // Address range: 0x80b0_0000 ~ 0x80bF_FFFF
        .wbs5_addr    (32'h80b0_0000),
        .wbs5_addr_msk(32'hFFF0_0000),

        .wbs5_adr_o(wbs5_adr_o),
        .wbs5_dat_i(wbs5_dat_i),
        .wbs5_dat_o(wbs5_dat_o),
        .wbs5_we_o (wbs5_we_o),
        .wbs5_sel_o(wbs5_sel_o),
        .wbs5_stb_o(wbs5_stb_o),
        .wbs5_ack_i(wbs5_ack_i),
        .wbs5_err_i('0),
        .wbs5_rty_i('0),
        .wbs5_cyc_o(wbs5_cyc_o),

        // Slave interface 6 (to clint controller)
        // Address range: 0x0200_0000 ~ 0x0200_FFFF
        .wbs6_addr    (32'h0200_0000),
        .wbs6_addr_msk(32'hFFFF_0000),

        .wbs6_adr_o(wbs6_adr_o),
        .wbs6_dat_i(wbs6_dat_i),
        .wbs6_dat_o(wbs6_dat_o),
        .wbs6_we_o (wbs6_we_o),
        .wbs6_sel_o(wbs6_sel_o),
        .wbs6_stb_o(wbs6_stb_o),
        .wbs6_ack_i(wbs6_ack_i),
        .wbs6_err_i('0),
        .wbs6_rty_i('0),
        .wbs6_cyc_o(wbs6_cyc_o),

        // Slave interface 7 (to UART controller)
        // Address range: 0x1000_0000 ~ 0x1000_FFFF
        .wbs7_addr    (32'h1000_0000),
        .wbs7_addr_msk(32'hFFFF_0000),

        .wbs7_adr_o(wbs7_adr_o),
        .wbs7_dat_i(wbs7_dat_i),
        .wbs7_dat_o(wbs7_dat_o),
        .wbs7_we_o (wbs7_we_o),
        .wbs7_sel_o(wbs7_sel_o),
        .wbs7_stb_o(wbs7_stb_o),
        .wbs7_ack_i(wbs7_ack_i),
        .wbs7_err_i('0),
        .wbs7_rty_i('0),
        .wbs7_cyc_o(wbs7_cyc_o)
    );

    bootloader bootloader_i (
        .clk(eth_clk),
        .rst(reset_eth_not_booted),

        .inst_we,
        .inst_addr,
        .inst_wdata,

        .mac_address,
        .ip_address,
        .solicited_ip_address,
        .solicited_mac_address,

        .wb_cyc_o(wbam_o[0].cyc),
        .wb_stb_o(wbam_o[0].stb),
        .wb_ack_i(wbam_i[0].ack),
        .wb_adr_o(wbam_o[0].adr),
        .wb_dat_o(wbam_o[0].dat),
        .wb_dat_i(wbam_i[0].dat),
        .wb_sel_o(wbam_o[0].sel),
        .wb_we_o(wbam_o[0].we),

        .finished(bootloader_finished)
    );

    wb_arbiter #(
        .MASTER_COUNT(3)
    ) wb_arbiter_i (
        .clk  (eth_clk),
        .rst  (reset_eth),
        .wbm_i(wbam_o),
        .wbm_o(wbam_i),
        .wbs_i(wbas_o),
        .wbs_o(wbas_i)
    );

    // TO BASE RAM
    sram_controller #(
        .SRAM_ADDR_WIDTH(21),
        .SRAM_DATA_WIDTH(32)
    ) sram_controller_base (
        .clk_i(eth_clk),
        .rst_i(reset_eth_not_booted),

        .wb_cyc_i(wbas_i.cyc),
        .wb_stb_i(wbas_i.stb),
        .wb_ack_o(wbas_o.ack),
        .wb_adr_i(wbas_i.adr),
        .wb_dat_i(wbas_i.dat),
        .wb_dat_o(wbas_o.dat),
        .wb_sel_i(wbas_i.sel),
        .wb_we_i (wbas_i.we),

        .sram_addr(base_ram_addr),
        .sram_data(base_ram_data),
        .sram_ce_n(base_ram_ce_n),
        .sram_oe_n(base_ram_oe_n),
        .sram_we_n(base_ram_we_n),
        .sram_be_n(base_ram_be_n)
    );

    entry_pool_controller entry_pool_controller_i (
        .clk(eth_clk),
        .rst(reset_eth),

        // Wishbone slave (to MUX)
        .wb_cyc_i(wbs1_cyc_o),
        .wb_stb_i(wbs1_stb_o),
        .wb_ack_o(wbs1_ack_i),
        .wb_adr_i(wbs1_adr_o),
        .wb_dat_i(wbs1_dat_o),
        .wb_dat_o(wbs1_dat_i),
        .wb_sel_i(wbs1_sel_o),
        .wb_we_i (wbs1_we_o),

        .bram_entry_addr(bram_entry_addr_cpu),
        .bram_entry_rdata(bram_entry_rdata_cpu),
        .bram_entry_wdata(bram_entry_wdata_cpu),
        .bram_entry_we(bram_entry_we_cpu)
    );

    next_hop_controller next_hop_controller_i (
        .clk(eth_clk),
        .rst(reset_eth),

        // Wishbone slave (to MUX)
        .wb_cyc_i(wbs2_cyc_o),
        .wb_stb_i(wbs2_stb_o),
        .wb_ack_o(wbs2_ack_i),
        .wb_adr_i(wbs2_adr_o),
        .wb_dat_i(wbs2_dat_o),
        .wb_dat_o(wbs2_dat_i),
        .wb_sel_i(wbs2_sel_o),
        .wb_we_i (wbs2_we_o),

        // to NEXT HOP POOL
        .next_hop_addr(next_hop_addr_cpu),
        .next_hop_rdata(next_hop_rdata_cpu),
        .next_hop_wdata(next_hop_wdata_cpu),
        .next_hop_we(next_hop_we_cpu)
    );

    node_pool_controller node_pool_controller_i (
        .clk(eth_clk),
        .rst(reset_eth),

        // Wishbone slave (to MUX)
        .wb_cyc_i(wbs3_cyc_o),
        .wb_stb_i(wbs3_stb_o),
        .wb_ack_o(wbs3_ack_i),
        .wb_adr_i(wbs3_adr_o),
        .wb_dat_i(wbs3_dat_o),
        .wb_dat_o(wbs3_dat_i),
        .wb_sel_i(wbs3_sel_o),
        .wb_we_i (wbs3_we_o),

        // to BRAM NODE
        .bram_node_addr(bram_node_addr_cpu),
        .bram_node_rdata(bram_node_rdata_cpu),
        .bram_node_wdata(bram_node_wdata_cpu),
        .bram_node_we(bram_node_we_cpu)
    );

    wire [8:0] dma_router_raddr;
    wire [31:0] dma_router_rdata;
    wire dma_router_read_finished;
    wire [10:0] dma_router_rlen;

    cpu2router_controller cpu2router_controller_i (
      .clk(eth_clk),
      .rst(reset_eth),

      .router_raddr(dma_router_raddr),
      .router_rdata(dma_router_rdata),
      .router_read_finished(dma_router_read_finished),
      .router_rlen(dma_router_rlen),

      .wb_cyc_i(wbs4_cyc_o),
      .wb_stb_i(wbs4_stb_o),
      .wb_ack_o(wbs4_ack_i),
      .wb_adr_i(wbs4_adr_o),
      .wb_dat_i(wbs4_dat_o),
      .wb_dat_o(wbs4_dat_i),
      .wb_sel_i(wbs4_sel_o),
      .wb_we_i (wbs4_we_o)
    );

    router2dma_sram router2dma_i (
        .clk(eth_clk),
        .rst(reset_eth),

        .wb_cyc_o(wbam_o[1].cyc),
        .wb_stb_o(wbam_o[1].stb),
        .wb_ack_i(wbam_i[1].ack),
        .wb_adr_o(wbam_o[1].adr),
        .wb_dat_o(wbam_o[1].dat),
        .wb_dat_i(wbam_i[1].dat),
        .wb_sel_o(wbam_o[1].sel),
        .wb_we_o(wbam_o[1].we),

        .internal_rx_data,
        .internal_rx_last,
        .internal_rx_user,
        .internal_rx_valid,
        .internal_rx_ready
    );

    dma2router dma2router_i (
        .clk(eth_clk),
        .rst(reset_eth),
        .router_raddr(dma_router_raddr),
        .router_rdata(dma_router_rdata),
        .router_read_finished(dma_router_read_finished),
        .router_rlen(dma_router_rlen),
        .internal_tx_data,
        .internal_tx_last,
        .internal_tx_user,
        .internal_tx_valid
    );

    dpy_controller dpy_controller_i (
        .clk(eth_clk),
        .rst(reset_eth),
        .dpy0,
        .dpy1,
        .wb_cyc_i(wbs5_cyc_o),
        .wb_stb_i(wbs5_stb_o),
        .wb_ack_o(wbs5_ack_i),
        .wb_adr_i(wbs5_adr_o),
        .wb_dat_i(wbs5_dat_o),
        .wb_dat_o(wbs5_dat_i),
        .wb_sel_i(wbs5_sel_o),
        .wb_we_i (wbs5_we_o)
    );

    clint_controller clint_controller_i (
        .clk_i(eth_clk),
        .rst_i(reset_eth),
        .wb_cyc_i(wbs6_cyc_o),
        .wb_stb_i(wbs6_stb_o),
        .wb_ack_o(wbs6_ack_i),
        .wb_adr_i(wbs6_adr_o),
        .wb_dat_i(wbs6_dat_o),
        .wb_dat_o(wbs6_dat_i),
        .wb_sel_i(wbs6_sel_o),
        .wb_we_i (wbs6_we_o)
    );

    uart_controller #(
        .CLK_FREQ(SYS_CLOCK_FREQ),
        .BAUD    (115200)
    ) uart_controller (
        .clk_i(eth_clk),
        .rst_i(reset_eth),

        .wb_cyc_i(wbs7_cyc_o),
        .wb_stb_i(wbs7_stb_o),
        .wb_ack_o(wbs7_ack_i),
        .wb_adr_i(wbs7_adr_o),
        .wb_dat_i(wbs7_dat_o),
        .wb_dat_o(wbs7_dat_i),
        .wb_sel_i(wbs7_sel_o),
        .wb_we_i (wbs7_we_o),

        .uart_txd_o(uart_tx),
        .uart_rxd_i(uart_rx)
    );

    wire [7:0] led_datapath;

    // README: Instantiate your datapath.
    frame_datapath
    #(
        .DATA_WIDTH(DATA_WIDTH),
        .ID_WIDTH(ID_WIDTH)
    )
    frame_datapath_i(
        .eth_clk(eth_clk),
        .reset(reset_eth),

        .BTN(BTN),
        .dip_sw(dip_sw),
        .touch_btn(touch_btn),
        .led(led[15:8]),

        .s_data(dp_rx_data),
        .s_keep(dp_rx_keep),
        .s_last(dp_rx_last),
        .s_user(dp_rx_user),
        .s_id(dp_rx_id),
        .s_valid(dp_rx_valid),
        .s_ready(dp_rx_ready),

        .m_data(dp_tx_data),
        .m_keep(dp_tx_keep),
        .m_last(dp_tx_last),
        .m_user(dp_tx_user),
        .m_dest(dp_tx_dest),
        .m_valid(dp_tx_valid),
        .m_ready(1'b1),

        .mac_address,
        .ip_address,
        .solicited_ip_address,
        .solicited_mac_address,

        .bram_node_addr(bram_node_addr_ft),
        .bram_node_data(bram_node_data_ft),
        .bram_entry_addr(bram_entry_addr_ft),
        .bram_entry_data(bram_entry_data_ft),
        .next_hop_addr(next_hop_addr_ft),
        .next_hop_data(next_hop_data_ft)

        // README: You will need to add some signals for your CPU to control the datapath,
        // or access the forwarding table or the address resolution cache.
    );

    wire [DATA_WIDTH - 1:0] eth_tx_data [0:4];
    wire [DATA_WIDTH / 8 - 1:0] eth_tx_keep [0:4];
    wire eth_tx_last [0:4];
    wire eth_tx_ready [0:4];
    wire [DATA_WIDTH / 8 - 1:0] eth_tx_user [0:4];
    wire eth_tx_valid [0:4];

    axis_interconnect_egress axis_interconnect_egress_i(
        .ACLK(eth_clk),
        .ARESETN(~reset_eth),

        .S00_AXIS_ACLK(eth_clk),
        .S00_AXIS_ARESETN(~reset_eth),
        .S00_AXIS_TVALID(dp_tx_valid),
        .S00_AXIS_TREADY(debug_egress_interconnect_ready),
        .S00_AXIS_TDATA(dp_tx_data),
        .S00_AXIS_TKEEP(dp_tx_keep),
        .S00_AXIS_TLAST(dp_tx_last),
        .S00_AXIS_TDEST(dp_tx_dest),
        .S00_AXIS_TUSER(dp_tx_user),

        .M00_AXIS_ACLK(eth_clk),
        .M00_AXIS_ARESETN(~reset_eth),
        .M00_AXIS_TVALID(eth_tx_valid[0]),
        .M00_AXIS_TREADY(eth_tx_ready[0]),
        .M00_AXIS_TDATA(eth_tx_data[0]),
        .M00_AXIS_TKEEP(eth_tx_keep[0]),
        .M00_AXIS_TLAST(eth_tx_last[0]),
        .M00_AXIS_TDEST(),
        .M00_AXIS_TUSER(eth_tx_user[0]),

        .M01_AXIS_ACLK(eth_clk),
        .M01_AXIS_ARESETN(~reset_eth),
        .M01_AXIS_TVALID(eth_tx_valid[1]),
        .M01_AXIS_TREADY(eth_tx_ready[1]),
        .M01_AXIS_TDATA(eth_tx_data[1]),
        .M01_AXIS_TKEEP(eth_tx_keep[1]),
        .M01_AXIS_TLAST(eth_tx_last[1]),
        .M01_AXIS_TDEST(),
        .M01_AXIS_TUSER(eth_tx_user[1]),

        .M02_AXIS_ACLK(eth_clk),
        .M02_AXIS_ARESETN(~reset_eth),
        .M02_AXIS_TVALID(eth_tx_valid[2]),
        .M02_AXIS_TREADY(eth_tx_ready[2]),
        .M02_AXIS_TDATA(eth_tx_data[2]),
        .M02_AXIS_TKEEP(eth_tx_keep[2]),
        .M02_AXIS_TLAST(eth_tx_last[2]),
        .M02_AXIS_TDEST(),
        .M02_AXIS_TUSER(eth_tx_user[2]),

        .M03_AXIS_ACLK(eth_clk),
        .M03_AXIS_ARESETN(~reset_eth),
        .M03_AXIS_TVALID(eth_tx_valid[3]),
        .M03_AXIS_TREADY(eth_tx_ready[3]),
        .M03_AXIS_TDATA(eth_tx_data[3]),
        .M03_AXIS_TKEEP(eth_tx_keep[3]),
        .M03_AXIS_TLAST(eth_tx_last[3]),
        .M03_AXIS_TDEST(),
        .M03_AXIS_TUSER(eth_tx_user[3]),

        .M04_AXIS_ACLK(eth_clk),
        .M04_AXIS_ARESETN(~reset_eth),
        .M04_AXIS_TVALID(eth_tx_valid[4]),
        .M04_AXIS_TREADY(eth_tx_ready[4]),
        .M04_AXIS_TDATA(eth_tx_data[4]),
        .M04_AXIS_TKEEP(eth_tx_keep[4]),
        .M04_AXIS_TLAST(eth_tx_last[4]),
        .M04_AXIS_TDEST(),
        .M04_AXIS_TUSER(eth_tx_user[4]),

        .S00_DECODE_ERR()
    );

    generate
        for (i = 0; i < 5; i = i + 1)
        begin
            egress_wrapper
            #(
                .DATA_WIDTH(DATA_WIDTH),
                .ID_WIDTH(ID_WIDTH)
            )
            egress_wrapper_i(
                .eth_clk(eth_clk),
                .reset(reset_eth),

                .s_data(eth_tx_data[i]),
                .s_keep(eth_tx_keep[i]),
                .s_last(eth_tx_last[i]),
                .s_user(eth_tx_user[i]),
                .s_valid(eth_tx_valid[i]),
                .s_ready(eth_tx_ready[i]),

                .m_data(eth_tx8_data[i]),
                .m_last(eth_tx8_last[i]),
                .m_user(eth_tx8_user[i]),
                .m_valid(eth_tx8_valid[i]),
                .m_ready(eth_tx8_ready[i])
            );
        end
    endgenerate

    led_delayer led_delayer_debug_i1(
        .clk(eth_clk),
        .reset(reset_eth),
        .in_led({1'b0, ~debug_egress_interconnect_ready,
                 ~debug_datapath_fifo_ready,
                 ~debug_ingress_interconnect_ready}),
        .out_led(led[7:0])
    );
endmodule
